# Generated by Django 5.2 on 2025-08-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('tariff', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новый пользователь'),
        ),
        migrations.AddField(
            model_name='user',
            name='next_tariff_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_tariff_planes', to='tariff.tariffplan', verbose_name='Следующий тариф'),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_datetime_pp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата&Время конца оплаченного периода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_datetime_pp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата&Время начала оплаченного периода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tariff_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariff_planes', to='tariff.tariffplan', verbose_name='Тариф'),
        ),
    ]
