# Generated by Django 5.2 on 2025-07-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='source.tariffplan', verbose_name='Тариф'),
        ),
    ]
