# Generated by Django 5.2 on 2025-09-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_tariff_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_tariff_planes', to='tariff.tariffplan', verbose_name='Следующий тариф'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariff_planes', to='tariff.tariffplan', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariffs',
            field=models.ManyToManyField(related_name='users', to='tariff.tariffplan', verbose_name='Все тарифы'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
