# Generated by Django 5.2 on 2025-10-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('address', '0012_alter_address_apartment_alter_address_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='ID автоплатежа'),
        ),
    ]
