# Generated by Django 5.2 on 2025-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_new_user_next_tariff_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_account',
            field=models.CharField(db_index=True, null=True, unique=True, verbose_name='Лс счет'),
        ),
    ]
