# Generated by Django 5.2 on 2025-08-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_tariff_plan'),
        ('tariff', '0004_tariffplan_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новый пользователь'),
        ),
        migrations.AddField(
            model_name='user',
            name='next_tariff_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_set_next_tariff_plan', to='tariff.tariffplan', verbose_name='Следующий тариф'),
        ),
    ]
