# Generated by Django 5.2 on 2025-05-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_account',
            field=models.CharField(default='', max_length=24, verbose_name='Лс счет'),
        ),
    ]
