# Generated by Django 5.2 on 2025-08-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_new_user_next_tariff_plan'),
        ('tariff', '0004_tariffplan_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='next_tariff_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set_next_tariff_plan', to='tariff.tariffplan', verbose_name='Следующий тариф'),
        ),
    ]
