# Generated by Django 5.2 on 2025-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fias',
            field=models.CharField(max_length=47, null=True, verbose_name='ФИАС'),
        ),
    ]
