# Generated by Django 5.2 on 2025-08-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_fias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_payment',
            field=models.BooleanField(default=False, verbose_name='Автооплата'),
        ),
    ]
