# Generated by Django 5.2 on 2026-05-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tariffs',
        ),
    ]
