# Generated by Django 5.2 on 2025-08-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_auto_payment'),
        ('address', '0005_rename_frame_address_building_address_fias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fias',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personal_account',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Адрес'),
        ),
    ]
