# Generated by Django 5.2 on 2026-05-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='Пользователь подтвержден'),
        ),
    ]
