# Generated by Django 5.2 on 2026-05-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвержден'),
        ),
    ]
