# Generated by Django 5.2 on 2025-08-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_apartment_remove_user_fias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal_account',
        ),
    ]
