# Generated by Django 5.2 on 2026-05-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_verified'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.definition'),
        ),
    ]
