# Generated by Django 5.2 on 2026-05-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
