# Generated by Django 5.2 on 2026-05-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
