# Generated by Django 5.2 on 2026-05-19 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_verified_user_is_verified'),
        ('address', '0034_address_apartment_sort_address_apartment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Адрес'),
        ),
    ]
