# Generated by Django 5.2 on 2026-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_operator',
            field=models.BooleanField(default=False),
        ),
    ]
