# Generated by Django 5.2 on 2026-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_client_operator_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(max_length=128, null=True, verbose_name='ФИО'),
        ),
    ]
