# Generated by Django 5.2 on 2025-09-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='id',
        ),
        migrations.AddField(
            model_name='promo',
            name='uuid',
            field=models.UUIDField(auto_created=True, default='b26e2d6c-d7ad-4fcd-87aa-46f5135114e9', primary_key=True, serialize=False, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
