# Generated by Django 5.2 on 2025-09-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_remove_promo_id_promo_uuid'),
        ('tariff', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='count',
        ),
        migrations.AddField(
            model_name='promo',
            name='tariff_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tariff.tariffplan', verbose_name='Тариф'),
            preserve_default=False,
        ),
    ]
