# Generated by Django 5.2 on 2025-06-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.CharField(default='', max_length=120, verbose_name='Id платежа'),
        ),
    ]
