# Generated by Django 5.2 on 2026-05-14 12:02

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0034_address_apartment_sort_address_apartment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20, verbose_name='Действие')),
                ('payload', models.JSONField(verbose_name='JSON')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
        migrations.CreateModel(
            name='DefinitionAddress',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('address.address',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, editable=False)),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Заводской номер')),
                ('username', models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='Логин устройства')),
                ('password', models.CharField(editable=False, max_length=256, null=True, verbose_name='Хеш пароль')),
                ('name', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Уникальное имя')),
                ('uniqueness', models.PositiveIntegerField(editable=False, verbose_name='Число для уникальности имени')),
                ('delete_at', models.DateTimeField(editable=False, null=True, verbose_name='Автоудаление через')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('isnot_online', models.BooleanField(editable=False, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.incompleteaddress', verbose_name='Адрес устройства')),
            ],
            options={
                'verbose_name': 'Устройство (MX210)',
                'verbose_name_plural': 'Устройства (MX210)',
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(editable=False, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Дискретный вход / Дискретный выход')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='device.device')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='device.definitionaddress', verbose_name='Квартира/Помещение')),
            ],
            options={
                'verbose_name': 'Порт',
                'verbose_name_plural': 'Порты',
                'constraints': [models.UniqueConstraint(fields=('device', 'port'), name='unique_device_port'), models.UniqueConstraint(fields=('address',), name='unique_address')],
            },
        ),
    ]
