# Generated by Django 5.2 on 2025-07-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='dev_name',
        ),
        migrations.AlterField(
            model_name='device',
            name='func',
            field=models.CharField(choices=[('SET', 'SET'), ('GET', 'GET')], default='', max_length=6, verbose_name='Функция'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Уникальное имя устройства в сети mqtt'),
        ),
    ]
