# Generated by Django 5.2 on 2026-05-20 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='port',
            field=models.IntegerField(editable=False, null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Дискретный вход / Дискретный выход'),
        ),
    ]
