# Generated by Django 5.2 on 2025-10-16 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_alter_address_apartment_alter_address_building_and_more'),
        ('device', '0003_definition_delete_encoard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='user',
        ),
        migrations.AddField(
            model_name='definition',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Дискретный вход / Дискретный выход'),
        ),
    ]
