# Generated by Django 5.2 on 2025-10-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_remove_definition_user_definition_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='device.device'),
        ),
    ]
