# Generated by Django 5.2 on 2025-09-01 18:47

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('pa', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Лицевой счет')),
                ('street', models.CharField(verbose_name='Улица')),
                ('house', models.CharField(blank=True, null=True, verbose_name='Дом')),
                ('building', models.CharField(blank=True, null=True, verbose_name='Корпус')),
                ('apartment', models.CharField(blank=True, null=True, verbose_name='Квартира')),
                ('fias', models.UUIDField(null=True, verbose_name='ФИАС')),
                ('join', models.CharField(null=True, verbose_name='Адрес')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['join'], name='address_add_join_2a86a7_gin')],
            },
        ),
    ]
