# Generated by Django 5.2 on 2025-08-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('pa', models.UUIDField(primary_key=True, serialize=False, verbose_name='Лицевой счет')),
                ('street', models.CharField(verbose_name='Улица')),
                ('house', models.CharField(verbose_name='Дом')),
                ('frame', models.CharField(blank=True, null=True, verbose_name='Корпус')),
                ('apartment', models.CharField(blank=True, null=True, verbose_name='Квартира')),
            ],
        ),
    ]
