# Generated by Django 5.2 on 2025-08-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_remove_address_pa_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='pa',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False, verbose_name='Лицевой счет'),
            preserve_default=False,
        ),
    ]
