# Generated by Django 5.2 on 2025-08-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_remove_address_id_address_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pa',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Лицевой счет'),
        ),
    ]
