# Generated by Django 5.2 on 2025-08-22 17:37

import address.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_pa'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fias',
            field=models.UUIDField(null=True, verbose_name='ФИАС'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pa',
            field=models.PositiveIntegerField(default=address.models._random_pa, primary_key=True, serialize=False, verbose_name='Лицевой счет'),
        ),
    ]
