# Generated by Django 5.2 on 2025-09-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_pa'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='address_add_join_2a86a7_gin',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='join',
            new_name='joinn',
        ),
    ]
