# Generated by Django 5.2 on 2025-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_fias_alter_address_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, null=True, verbose_name='Дом'),
        ),
    ]
