# Generated by Django 5.2 on 2025-09-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_address_address_add_join_2a86a7_gin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='joinn',
            new_name='join',
        ),
    ]
