# Generated by Django 5.2 on 2025-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_rename_joinn_address_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='join',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Улица'),
        ),
    ]
