# Generated by Django 5.2 on 2025-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_address_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='join',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
