# Generated by Django 5.2 on 2025-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_address_apartment_alter_address_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='join',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
    ]
