# Generated by Django 5.2 on 2025-08-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_address_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='join',
            field=models.TextField(default='', editable=False),
        ),
    ]
