# Generated by Django 5.2 on 2025-08-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='join',
        ),
    ]
