# Generated by Django 5.2 on 2025-09-01 19:08

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='join',
            field=django.contrib.postgres.search.SearchVectorField(max_length=255, verbose_name='Адрес'),
        ),
    ]
