# Generated by Django 5.2 on 2025-08-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_remove_address_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='frame',
            new_name='building',
        ),
    ]
