# Generated by Django 5.2 on 2025-09-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_alter_address_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='join',
            field=models.TextField(max_length=255, verbose_name='Адрес'),
        ),
    ]
