# Generated by Django 5.2 on 2025-09-01 19:30

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_alter_address_join'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['join'], name='address_add_join_d0f19f_btree'),
        ),
    ]
