# Generated by Django 5.2 on 2025-10-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_address_address_add_join_d0f19f_btree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=6, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=6, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=6, verbose_name='Дом'),
        ),
    ]
