# Generated by Django 5.2 on 2025-10-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_alter_address_apartment_alter_address_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Москва', max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
