# Generated by Django 5.2 on 2025-10-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pa',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Лицевой счет'),
        ),
    ]
