# Generated by Django 5.2 on 2026-03-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_alter_address_pa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompleteAddress',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('address.address',),
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['join']},
        ),
    ]
