# Generated by Django 5.2 on 2026-03-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0015_incompleteaddress_alter_address_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Квартира'),
        ),
    ]
