# Generated by Django 5.2 on 2026-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_alter_address_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Корпус'),
        ),
    ]
