# Generated by Django 5.2 on 2026-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0017_alter_address_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=64, verbose_name='Дом'),
        ),
    ]
