# Generated by Django 5.2 on 2026-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0018_alter_address_apartment_alter_address_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pa_seed',
            field=models.PositiveBigIntegerField(null=True, unique=True, verbose_name='Сид лицевого счета'),
        ),
    ]
