# Generated by Django 5.2 on 2026-03-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0019_address_pa_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building',
        ),
        migrations.RemoveField(
            model_name='address',
            name='pa_seed',
        ),
        migrations.AlterField(
            model_name='address',
            name='pa',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ID Лицевого счета'),
        ),
    ]
