# Generated by Django 5.2 on 2026-03-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_remove_address_building_remove_address_pa_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='fias',
            field=models.UUIDField(unique=True, verbose_name='ФИАС'),
        ),
    ]
