# Generated by Django 5.2 on 2026-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0021_alter_address_fias'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='seed',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True, verbose_name='Сид лицевого счета'),
            preserve_default=False,
        ),
    ]
