# Generated by Django 5.2 on 2026-03-26 19:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0022_address_seed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='address_add_join_d0f19f_btree',
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['join'], name='join_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
