# Generated by Django 5.2 on 2026-03-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0023_remove_address_address_add_join_d0f19f_btree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='join_trgm_idx',
        ),
    ]
