# Generated by Django 5.2 on 2026-03-26 19:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0024_alter_address_options_remove_address_join_trgm_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['join']},
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['join'], name='join_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
