# Generated by Django 5.2 on 2026-03-26 20:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0025_alter_address_options_address_join_trgm_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='join_trgm_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='join',
            new_name='full',
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full'], name='full_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
