# Generated by Django 5.2 on 2026-03-26 20:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0026_alter_address_options_remove_address_join_trgm_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='full_trgm_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='full',
            new_name='line',
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['line'], name='line_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
