# Generated by Django 5.2 on 2026-03-26 20:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0027_remove_address_full_trgm_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='line_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GistIndex(fields=['line'], name='line_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
    ]
