# Generated by Django 5.2 on 2026-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0028_remove_address_line_trgm_idx_address_line_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(editable=False, max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='fias',
            field=models.UUIDField(editable=False, unique=True, verbose_name='ФИАС'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line',
            field=models.TextField(editable=False, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pa',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='ID Лицевого счета'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(editable=False, max_length=64, verbose_name='Улица'),
        ),
    ]
