# Generated by Django 5.2 on 2026-03-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0029_alter_address_apartment_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес (FIAS)', 'verbose_name_plural': 'Адреса (FIAS)'},
        ),
        migrations.AlterModelOptions(
            name='incompleteaddress',
            options={'verbose_name': 'Адрес (дома/строения)', 'verbose_name_plural': 'Адреса (дома/строения)'},
        ),
    ]
