# Generated by Django 5.2 on 2026-03-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0030_alter_address_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAddress',
            fields=[
            ],
            options={
                'verbose_name': 'Адрес (квартиры/помещения)',
                'verbose_name_plural': 'Адреса (квартиры/помешения)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('address.address',),
        ),
        migrations.AddField(
            model_name='address',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
