# Generated by Django 5.2 on 2026-03-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0031_apartmentaddress_address_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentAddress',
        ),
    ]
