# Generated by Django 5.2 on 2026-03-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0032_delete_apartmentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='parent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
