# Generated by Django 5.2 on 2026-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0033_alter_address_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment_sort',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Номер квартиры в числовом формате'),
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_type',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, verbose_name='Тип помещения'),
        ),
    ]
