# Generated by Django 5.2 on 2026-05-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0034_address_apartment_sort_address_apartment_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='line_trgm_idx',
        ),
    ]
