# Generated by Django 5.2 on 2026-05-23 13:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0035_remove_address_line_trgm_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GistIndex(fields=['line'], name='line_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
    ]
