# Generated by Django 5.2 on 2025-09-23 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, verbose_name='UUID тарифа')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Поле Цена в рублях')),
                ('archive', models.BooleanField(default=False, verbose_name='Признак архивности')),
                ('unit_measurement', models.CharField(choices=[('day', 'день'), ('month', 'месяц'), ('two month', 'два месяца'), ('quarter', 'квартал'), ('halfyear', 'полгода'), ('year', 'год'), ('constant', 'навсегда')], max_length=9, verbose_name='Единица измерения')),
                ('is_test', models.BooleanField(default=False, verbose_name='Тестовый тариф')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='ServiceArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime_pp', models.DateTimeField(verbose_name='Дата&Время начала оплаченного периода')),
                ('end_datetime_pp', models.DateTimeField(verbose_name='Дата&Время конца оплаченного периода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_archive', to=settings.AUTH_USER_MODEL)),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tariff.tariffplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Архив услуг',
                'verbose_name_plural': 'Архивы услуг',
            },
        ),
    ]
