# Generated by Django 5.2 on 2026-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_tariffplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffplan',
            name='unit_measurement',
            field=models.CharField(choices=[('день', 'Day'), ('месяц', 'Month'), ('два месяца', 'Two Month'), ('квартал', 'Quarter'), ('полгода', 'Halfyear'), ('год', 'Year'), ('навсегда', 'Constant')], max_length=12, verbose_name='Единица измерения'),
        ),
    ]
