# Generated by Django 5.2 on 2025-08-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0003_alter_tariffplan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffplan',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Тестовый тариф'),
        ),
    ]
