# Generated by Django 5.2 on 2026-05-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0004_alter_tariffplan_unit_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffplan',
            name='unit_measurement',
            field=models.CharField(choices=[('day', 'день'), ('month', 'месяц'), ('two_month', 'два месяца'), ('quarter', 'квартал'), ('halfyear', 'полгода'), ('year', 'год'), ('constant', 'навсегда')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
