# Generated by Django 5.2 on 2025-07-16 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.BigIntegerField(verbose_name='Заводской номер')),
                ('dev_name', models.CharField(max_length=100, verbose_name='Название устройства')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('path', models.CharField(max_length=255, verbose_name='Путь MQTT')),
                ('offset', models.SmallIntegerField(verbose_name='Сдвиг')),
            ],
        ),
        migrations.CreateModel(
            name='Encoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Дискретный вход / Дискретный выход')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt_executor.device')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='encoarded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
